global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'users'
    static_configs:
      - targets: ['host.docker.internal:9091']