environment: development
name: users
version: 1.0.0
server:
  address: ":50051"
  port: 50051
  cache_refresh_interval_day: 7
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 10s
  max_connections: 1000
  max_concurrent_streams: 100
  enable_reflection: true
  enable_health_check: true
  connection_timeout: 10s
  keepalive_time: 10s
  keepalive_timeout: 3s
  max_connection_idle: 5m
  max_connection_age: 10m
  max_connection_age_grace: 5s
  max_recv_msg_size: 4194304  # 4MB
  max_send_msg_size: 4194304  # 4MB
database:
  url: "postgres://root:Hl7FudwaSNzOhhioo0GxlmmMD0LM+I8StQIqJCZ1TPg@localhost:5432/users?sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m
  conn_max_idle_time: 10m
  health_check_period: 1m
  connection_timeout: 10s
  query_timeout: 30s
logging:
  level: debug
  format: console
  output: stdout
  structured: false
metrics:
  enabled: true
  address: "0.0.0.0:9091"
  path: "/metrics"
security:
  enable_tls: false
  tls_cert_file: ""
  tls_key_file: ""
  trusted_proxies: []
  rate_limit_rps: 1000
  rate_limit_burst: 2000
  max_request_size: 4194304  # 4MB
  enable_cors: true
  allowed_origins: ["*"]