services:
  db:
    image: postgres:16 # Or postgres:15, postgres:14
    environment:
      POSTGRES_DB: reservation
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Hl7FudwaSNzOhhioo0GxlmmMD0LM+I8StQIqJCZ1TPg
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: