apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app: users-service
      app.kubernetes.io/name: users-service
      component: backend
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  app.kubernetes.io/name: users-service
  app.kubernetes.io/component: backend

images:
  - name: users-service # ต้องเป็นชื่อเดียวกับใน deployment.yaml ก่อนการ patch
    newTag: latest # Placeholder tag
