apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-app-dev

resources:
  - ../../base
  - service-accounts.yaml

images:
  - name: users-service # ต้องตรงกับชื่อใน base/kustomization.yaml
    newName: users-service
    newTag: dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: users-service
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: users-service-config

labels:
  - pairs:
      environment: dev
    includeSelectors: true
    includeTemplates: true
