apiVersion: v1
kind: Secret
metadata:
  name: users-service-secret
  labels:
    app: users-service
    app.kubernetes.io/name: users-service
    component: backend
type: Opaque
data:
  # Base64-encoded values
  # DB_USERNAME: "dXNlcm5hbWU="
  # DB_PASSWORD: "cGFzc3dvcmQ="
  # JWT_SECRET: "c2VjcmV0LWtleQ=="
