# k8s/base/api-gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
type: Opaque
data:
  # Add base64 encoded secrets here
  # DATABASE_PASSWORD: ""
  # JWT_SECRET: ""
